services:
  - type: web
    name: intuitive-py
    env: python
    repo: https://github.com/scosme20/Processo-seletivo/tree/main/python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 4 -b 0.0.0.0:10000 app:app"
    plan: free
    autoDeploy: true
